version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir:  /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=db"
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8081:80
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    ports:
      - '5436:5432'
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: